### ISSUE TITLE
[ERROR]: Example at https://milvus.io/docs/manage_connection.md has an error

### ISSUE THREAD

**Issue by abawany** [milvus-io/milvus-docs#2420]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

At https://milvus.io/docs/manage_connection.md there is an error vs. the currently-available Python sdk:

In the section `Connect a Milvus Server`, the example shows:

```
# Run `python3` in your terminal to operate in the Python interactive mode.
from pymilvus import connections
connections.connect(
  alias="default",
  uri="localhost:19530",
  token="root:Milvus",
)
```

This fails as follows:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/pymilvus/orm/connections.py", line 395, in connect
    addr, parsed_uri = self.__get_full_address(*config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymilvus/orm/connections.py", line 257, in __get_full_address
    address, parsed = self.__parse_address_from_uri(uri)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymilvus/orm/connections.py", line 176, in __parse_address_from_uri
    raise ConnectionConfigException(message=f"{illegal_uri_msg.format(uri)}") from None
pymilvus.exceptions.ConnectionConfigException: <ConnectionConfigException: (code=1, message=Illegal uri: [localhost:19530], expected form 'http[s]://[user:password@]example.com[:12345]')>
```

### Suggestion

The SDK error provides the best suggestion:

```
expected form 'http[s]://[user:password@]example.com[:12345]'
```

for the `uri` parameter in this example. When the line in the above example was changed to `connections.connect(alias="default", uri="http://localhost:19530", token="root:Milvus",)` the example worked as expected.

**Comment by shubham0204** [comment]
Experienced the same error today, and adding `http://localhost:19530` to `uri` works instead of `localhost:19530` mentioned in the docs.
